Support for Non ROSA AWS deployments-2

diff --git a/automation-roles/30-provision-infra/provision-aws/tasks/provision-self-managed.yml b/automation-roles/30-provision-infra/provision-aws/tasks/provision-self-managed.yml
--- a/automation-roles/30-provision-infra/provision-aws/tasks/provision-self-managed.yml
+++ b/automation-roles/30-provision-infra/provision-aws/tasks/provision-self-managed.yml
@@ -10,11 +10,6 @@
 
 - name: Provision AWS VPC Infrastructure
   block:
-  - name: "Copy variables to aws directory {{status_dir}}/aws"
-    template:
-      src: 'variables.auto.tfvars.j2'
-      dest: '{{status_dir}}/aws/variables.auto.tfvars'
-
   - name: "Copy terraform.tfvars to aws directory {{status_dir}}/aws"
     template:
       src: 'terraform.tfvars.j2'
@@ -28,14 +23,80 @@
   - name: "Run terraform init in aws directory {{status_dir}}/aws"
     shell: 
       chdir: '{{status_dir}}/aws'
-      cmd: 'terraform init'
+      cmd: terraform init        
 
   - name: "Run terraform plan in aws directory {{status_dir}}/aws, check {{status_dir}}/aws/plan.log"
     shell: |
       set -o pipefail
+      export AWS_ACCESS_KEY_ID={{_aws_access_key}} > /dev/null
+      export AWS_SECRET_ACCESS_KEY={{_aws_secret_access_key}} /dev/null
+      export AWS_DEFAULT_REGION={{aws_region}} /dev/null
       terraform plan -no-color -detailed-exitcode 2>&1 \
         | tee {{status_dir}}/aws/plan.log
     args:
       chdir: "{{status_dir}}/aws"
     register: _terraform_plan_result
     failed_when: "_terraform_plan_result.rc == 1"
+
+  # # If there are no changes, terraform plan will return with exit code 2 (as per -detailed-exitcode)
+  # # Subsequent steps are skipped if no changes were planned
+  # - name: Determine if any changes will be made in the terraform apply
+  #   debug:
+  #     msg: "No changes were detected in the planning phase, apply will be skipped and tfstate secret will not be updated"
+  #   when: "_terraform_plan_result.rc == 0"
+
+  # - set_fact:
+  #     _plan_log: "{{ lookup('file', status_dir + '/aws/plan.log') }}"
+
+  # - set_fact:
+  #     _destroy_result: "{{ _plan_log | regex_search('([0-9]+) to destroy', '\\1') }}"
+
+  # - set_fact:
+  #     _number_to_destroy: "{{ _destroy_result | first }}"
+  #   when: _destroy_result != ''
+
+  # - name: Show number of artifacts to destroy
+  #   debug:
+  #     var: _number_to_destroy
+  #   when: _number_to_destroy is defined
+
+  # - name: Fail if terraform plans to destroy artifacts and this was not confirmed at the command line
+  #   fail:
+  #     msg: 
+  #     - "Terraform will destroy artifacts and this was not confirmed"
+  #     - "{{ _plan_log }}"
+  #   when:
+  #     - _number_to_destroy is defined
+  #     - _number_to_destroy != '0'
+  #     - confirm_destroy | bool != True
+
+  # - name: "Run terraform apply in Terraform directory {{status_dir}}/terraform, check {{status_dir}}/terraform/apply.log"
+  #   shell: |
+  #     set -o pipefail
+  #     terraform apply -auto-approve -no-color 2>&1 \
+  #       | tee {{status_dir}}/aws/apply.log
+  #   args:
+  #     chdir: "{{status_dir}}/aws"
+  #   environment:
+  #     TF_LOG: "info"
+  #     TF_LOG_PATH: "{{ status_dir }}/aws/tf_apply.log"
+  #   register: _terraform_apply_result
+  #   ignore_errors: yes
+  #   when: _terraform_plan_result.rc != 0
+
+  # - name: Store the terraform tfstate file as secret {{ environment_name }}-terraform-tfstate in group {{ environment_name }}
+  #   include_role:
+  #     name: vault-set-secret
+  #   vars:
+  #     secret_name: "{{ environment_name }}-terraform-tfstate"
+  #     secret_group: "{{ environment_name }}"
+  #     secret_file: "{{ status_dir }}/aws/terraform.tfstate"
+  #   when: 
+  #   - _terraform_plan_result.rc != 0
+
+  # - name: Fail if there were errors during the terraform apply
+  #   fail:
+  #     msg: Error occurred during Terraform apply, state has been preserved. Failing now. Check the apply log for details.
+  #   when: 
+  #   - _terraform_plan_result.rc == 2
+  #   - _terraform_apply_result.rc!=0
